WINE_QUALITY_SCHEMA: dict[str, str] = {
    "fixed acidity": "float",
    "volatile acidity": "float",
    "citric acid": "float",
    "residual sugar": "float",
    "chlorides": "float",
    "free sulfur dioxide": "int",
    "total sulfur dioxide": "int",
    "density": "float",
    "pH": "float",
    "sulphates": "float",
    "alcohol": "float",
    "quality": "int",
    "Id": "int",
}